spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${secret.datasource.url}
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
