global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']  # Linux면 호스트 IP/컨테이너 이름